# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chequeMiCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chequeMiCode
  pod 'RNMobileCenterShared', '~> 0.11.2'

  

  target 'chequeMiCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chequeMiCode-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for chequeMiCode-tvOS

  target 'chequeMiCode-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
